# Generated by Django 4.2.4 on 2023-08-17 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_display',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=30)),
                ('f_protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('f_calories', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_protein', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_carbs', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_calories', models.DecimalField(decimal_places=2, max_digits=6)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macrosweb.food_display')),
            ],
        ),
    ]
