# Generated by Django 4.2.4 on 2023-08-17 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrosweb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
