# Generated by Django 4.2.4 on 2023-08-17 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('macrosweb', '0002_delete_stats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food_display',
            old_name='f_carbs',
            new_name='carbs',
        ),
        migrations.RenameField(
            model_name='food_display',
            old_name='f_fat',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='food_display',
            old_name='food_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='food_display',
            old_name='f_protein',
            new_name='protein',
        ),
        migrations.RemoveField(
            model_name='food_display',
            name='f_calories',
        ),
    ]
